### ISSUE TITLE
syncnet error

### ISSUE THREAD

**Issue by yanghedada** [bytedance/LatentSync#4]
Traceback (most recent call last):
  File "/home/work/miniforge3/envs/latentsync/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/work/miniforge3/envs/latentsync/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/work/LatentSync/scripts/train_unet.py", line 512, in <module>
    main(config)
  File "/home/work/LatentSync/scripts/train_unet.py", line 388, in main
    vision_embeds, audio_embeds = syncnet(syncnet_input, mel)
  File "/home/work/miniforge3/envs/latentsync/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/work/miniforge3/envs/latentsync/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/work/LatentSync/latentsync/models/syncnet.py", line 51, in forward
    vision_embeds = self.visual_encoder(image_sequences)  # (b, c, 1, 1)
  File "/home/work/miniforge3/envs/latentsync/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/work/miniforge3/envs/latentsync/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/work/LatentSync/latentsync/models/syncnet.py", line 223, in forward
    hidden_states = self.conv_in(hidden_states)
  File "/home/work/miniforge3/envs/latentsync/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/work/miniforge3/envs/latentsync/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/work/miniforge3/envs/latentsync/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/work/miniforge3/envs/latentsync/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 48, 3, 3], expected input[4, 64, 16, 32] to have 48 channels, but got 64 channels instead

**Comment by chunyu-li** [comment]
What did you change in configs/syncnet/syncnet_16_pixel.yaml? You should make sure the in_channels of SyncNet is equal to num_frames x 3 for pixel space SyncNet or num_frames x 4 for latent space SyncNet.

**Comment by yanghedada** [comment]
change nothtion!

**Comment by chunyu-li** [comment]
This is syncnet_16_latent.yaml, you should use syncnet_16_pixel.yaml

**Comment by yanghedada** [comment]
## syncnet_16_pixel.yaml 
`model:
  audio_encoder: # input (1, 80, 52)
    in_channels: 1
    block_out_channels: [32, 64, 128, 256, 512, 1024, 2048]
    downsample_factors: [[2, 1], 2, 2, 1, 2, 2, [2, 3]]
    attn_blocks: [0, 0, 0, 0, 0, 0, 0]
    dropout: 0.0
  visual_encoder: # input (48, 128, 256)
    in_channels: 48
    block_out_channels: [64, 128, 256, 256, 512, 1024, 2048, 2048]
    downsample_factors: [[1, 2], 2, 2, 2, 2, 2, 2, 2]
    attn_blocks: [0, 0, 0, 0, 0, 0, 0, 0]
    dropout: 0.0

ckpt:
  resume_ckpt_path: ""
  inference_ckpt_path: checkpoints/latentsync_syncnet.pt
  save_ckpt_steps: 2500

data:
  train_output_dir: debug/syncnet
  num_val_samples: 2048
  batch_size: 128 # 128
  num_workers: 11 # 11
  latent_space: false
  num_frames: 16
  resolution: 256
  train_fileslist: /mnt/bn/maliva-gen-ai-v2/chunyu.li/fileslist/all_data_v6.txt
  train_data_dir: ""
  val_fileslist: ""
  val_data_dir: /mnt/bn/maliva-gen-ai-v2/chunyu.li/VoxCeleb2/high_visual_quality/val
  audio_cache_dir: /mnt/bn/maliva-gen-ai-v2/chunyu.li/audio_cache/mel_new
  lower_half: true
  audio_sample_rate: 16000
  video_fps: 25

optimizer:
  lr: 1e-5
  max_grad_norm: 1.0

run:
  max_train_steps: 10000000
  validation_steps: 2500
  mixed_precision_training: true
  seed: 42
`

**Comment by yanghedada** [comment]
The first_stage.yaml specifies syncnet_16_pixel.yaml. When training  with all default settings, it results in errors.
`data:
  syncnet_config_path: configs/syncnet/syncnet_16_pixel.yaml
  train_output_dir: debug/unet
  train_fileslist: /mnt/bn/maliva-gen-ai-v2/chunyu.li/fileslist/all_data_v6.txt
  train_data_dir: ""
  audio_cache_dir: /mnt/bn/maliva-gen-ai-v2/chunyu.li/audio_cache/whisper_new

  val_video_path: assets/demo1_video.mp4
  val_audio_path: assets/demo1_audio.wav
  batch_size: 8 # 8
  num_workers: 11 # 11
  num_frames: 16
  resolution: 256
  mask: fix_mask
  audio_sample_rate: 16000
  video_fps: 25

ckpt:
  resume_ckpt_path: checkpoints/latentsync_unet.pt
  save_ckpt_steps: 5000

run:
  pixel_space_supervise: false
  use_syncnet: true
  sync_loss_weight: 0.05 # 1/283
  perceptual_loss_weight: 0.1 # 0.1
  recon_loss_weight: 1 # 1
  guidance_scale: 1.0 # 1.5 or 1.0
  trepa_loss_weight: 10
  inference_steps: 20
  seed: 1247
  use_mixed_noise: true
  mixed_noise_alpha: 1 # 1
  mixed_precision_training: true
  enable_gradient_checkpointing: false
  enable_xformers_memory_efficient_attention: true
  max_train_steps: 10000000
  max_train_epochs: -1

optimizer:
  lr: 1e-5
  scale_lr: false
  max_grad_norm: 1.0
  lr_scheduler: constant
  lr_warmup_steps: 0

model:
  act_fn: silu
  add_audio_layer: true
  custom_audio_layer: false
  audio_condition_method: cross_attn # Choose between [cross_attn, group_norm]
  attention_head_dim: 8
  block_out_channels: [320, 640, 1280, 1280]
  center_input_sample: false
  cross_attention_dim: 384
  down_block_types:
    [
      "CrossAttnDownBlock3D",
      "CrossAttnDownBlock3D",
      "CrossAttnDownBlock3D",
      "DownBlock3D",
    ]
  mid_block_type: UNetMidBlock3DCrossAttn
  up_block_types:
    [
      "UpBlock3D",
      "CrossAttnUpBlock3D",
      "CrossAttnUpBlock3D",
      "CrossAttnUpBlock3D",
    ]
  downsample_padding: 1
  flip_sin_to_cos: true
  freq_shift: 0
  in_channels: 13 # 49
  layers_per_block: 2
  mid_block_scale_factor: 1
  norm_eps: 1e-5
  norm_num_groups: 32
  out_channels: 4 # 16
  sample_size: 64
  resnet_time_scale_shift: default # Choose between [default, scale_shift]
  unet_use_cross_frame_attention: false
  unet_use_temporal_attention: false

  # Actually we don't use the motion module in the final version of LatentSync
  # When we started the project, we used the codebase of AnimateDiff and tried motion module
  # But the results are poor, and we decied to leave the code here for possible future usage
  use_motion_module: false
  motion_module_resolutions: [1, 2, 4, 8]
  motion_module_mid_block: false
  motion_module_decoder_only: false
  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads: 8
    num_transformer_block: 1
    attention_block_types:
      - Temporal_Self
      - Temporal_Self
    temporal_position_encoding: true
    temporal_position_encoding_max_len: 16
    temporal_attention_dim_div: 1
    zero_initialize: true
`

**Comment by chunyu-li** [comment]
1. Are you training SyncNet or U-Net?
2. You need to change `train_fileslist` and `audio_cache_dir ` to your own path

By the way, please copy the error information here so that I can help you

**Comment by yanghedada** [comment]
### only train U-Net
first_stage.yaml
`
run:
  pixel_space_supervise: false
  use_syncnet: **true**
`


S3FD] finished loading (0.2911 sec)
{'only_cross_attention', 'dual_cross_attention', 'upcast_attention', 'num_class_embeds', 'use_inflated_groupnorm', 'class_embed_type', 'use_linear_projection'} was not found in config. Values will be initialized to default values.
12/25/2024 18:01:09 - INFO - latentsync.models.unet - Load from checkpoint: checkpoints/latentsync_unet.pt
12/25/2024 18:01:16 - INFO - __main__ - trainable params number: 686
12/25/2024 18:01:16 - INFO - __main__ - trainable params scale: 849.962 M
12/25/2024 18:01:18 - INFO - __main__ - ***** Running training *****
12/25/2024 18:01:18 - INFO - __main__ -   Num examples = 3800
12/25/2024 18:01:18 - INFO - __main__ -   Num Epochs = 10527
12/25/2024 18:01:18 - INFO - __main__ -   Instantaneous batch size per device = 2
12/25/2024 18:01:18 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 4
12/25/2024 18:01:18 - INFO - __main__ -   Total optimization steps = 10000000
Steps:   0%|                                                                                                                                                                                                                                                 | 0/10000000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/work/miniforge3/envs/latentsync/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/work/miniforge3/envs/latentsync/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/workLatentSync/scripts/train_unet.py", line 512, in <module>
    main(config)
  File "/home/workLatentSync/scripts/train_unet.py", line 388, in main
    vision_embeds, audio_embeds = syncnet(syncnet_input, mel)
  File "/home/work/miniforge3/envs/latentsync/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/work/miniforge3/envs/latentsync/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/workLatentSync/latentsync/models/syncnet.py", line 51, in forward
    vision_embeds = self.visual_encoder(image_sequences)  # (b, c, 1, 1)
  File "/home/work/miniforge3/envs/latentsync/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/work/miniforge3/envs/latentsync/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/workLatentSync/latentsync/models/syncnet.py", line 223, in forward[lost server]
    hidden_states = self.conv_in(hidden_states)                                                       (base) [work@c3-ai-g8v100v6-vision01 ~]$ 
  File "/home/work/miniforge3/envs/latentsync/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/work/miniforge3/envs/latentsync/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/work/miniforge3/envs/latentsync/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/work/miniforge3/envs/latentsync/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 48, 3, 3], expected input[2, 64, 16, 32] to have 48 channels, but got 64 channels instead
Steps:   0%|                                                                                                                                                                                                                                                 | 0/10000000 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/home/work/miniforge3/envs/latentsync/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/work/miniforge3/envs/latentsync/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/workLatentSync/scripts/train_unet.py", line 512, in <module>
    main(config)
  File "/home/workLatentSync/scripts/train_unet.py", line 388, in main
    vision_embeds, audio_embeds = syncnet(syncnet_input, mel)
  File "/home/work/miniforge3/envs/latentsync/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/work/miniforge3/envs/latentsync/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/workLatentSync/latentsync/models/syncnet.py", line 51, in forward
    vision_embeds = self.visual_encoder(image_sequences)  # (b, c, 1, 1)
  File "/home/work/miniforge3/envs/latentsync/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/work/miniforge3/envs/latentsync/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/workLatentSync/latentsync/models/syncnet.py", line 223, in forward
    hidden_states = self.conv_in(hidden_states)
  File "/home/work/miniforge3/envs/latentsync/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
[0] 0:[tmux]*Z

**Comment by chunyu-li** [comment]
For the first stage training, `pixel_space_supervise` and `use_syncnet` should be set to `false`, please pull the latest code.

**Comment by yanghedada** [comment]
Get~

**Comment by fenghe12** [comment]
how to prepare train data for syncnet? I just saw data preprocessing pipeline

**Comment by yanghedada** [comment]
@chunyu-li Is the datasets of train_syncnet  the same as train_unet?

**Comment by chunyu-li** [comment]
> how to prepare train data for syncnet? I just saw data preprocessing pipeline

The data processing pipelines for unet and syncnet are the same

**Comment by chunyu-li** [comment]
> @chunyu-li Is the datasets of train_syncnet the same as train_unet?

Yes

**Comment by qianchiyu** [comment]
error Connection errored out.,远程主机关闭一个链接怎么回事,现在不能用了
